[2024-12-02T14:22:31.675+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T14:22:31.692+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:22:26.964261+00:00 [queued]>
[2024-12-02T14:22:31.701+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:22:26.964261+00:00 [queued]>
[2024-12-02T14:22:31.702+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T14:22:31.719+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 09:22:26.964261+00:00
[2024-12-02T14:22:31.730+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=52326) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T14:22:31.732+0500] {standard_task_runner.py:72} INFO - Started process 52332 to run task
[2024-12-02T14:22:31.735+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T09:22:26.964261+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmp4tfp4ebi']
[2024-12-02T14:22:31.741+0500] {standard_task_runner.py:105} INFO - Job 23: Subtask extract_from_api
[2024-12-02T14:22:31.804+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T09:22:26.964261+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T14:22:31.905+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T09:22:26.964261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T09:22:26.964261+00:00'
[2024-12-02T14:22:31.907+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T14:22:31.934+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?
[2024-12-02T14:22:31.935+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?lat=31.5204&lon=74.3587&appid=7ffe28e7eea4bb7870bd861ff09cfb80
[2024-12-02T14:22:31.936+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T14:23:27.183+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-12-02T14:23:27.186+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T14:23:27.212+0500] {process_utils.py:132} INFO - Sending 15 to group 52332. PIDs of all processes in the group: [52332]
[2024-12-02T14:23:27.212+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 52332
[2024-12-02T14:24:27.236+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=52332, name='python3.12', status='running', started='14:22:31') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T14:24:27.237+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 52332
[2024-12-02T14:24:27.245+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=52332, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='14:22:31') (52332) terminated with exit code -9
[2024-12-02T14:24:27.246+0500] {standard_task_runner.py:190} ERROR - ('Job 23 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
