[2024-12-02T13:40:51.120+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T13:40:51.133+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:40:46.531523+00:00 [queued]>
[2024-12-02T13:40:51.140+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:40:46.531523+00:00 [queued]>
[2024-12-02T13:40:51.140+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-02T13:40:51.152+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_from_api> on 2024-12-02 08:40:46.531523+00:00
[2024-12-02T13:40:51.160+0500] {logging_mixin.py:190} WARNING - /Users/hanan-nawaz/Documents/Projects/Pakistan_AQI_Analysis/myenv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=49553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T13:40:51.162+0500] {standard_task_runner.py:72} INFO - Started process 49559 to run task
[2024-12-02T13:40:51.164+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_open_weather', 'extract_from_api', 'manual__2024-12-02T08:40:46.531523+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/qc/y2_zkt8d01zf90dfpf72dm400000gn/T/tmpdyivsvyi']
[2024-12-02T13:40:51.168+0500] {standard_task_runner.py:105} INFO - Job 14: Subtask extract_from_api
[2024-12-02T13:40:51.217+0500] {task_command.py:467} INFO - Running <TaskInstance: etl_open_weather.extract_from_api manual__2024-12-02T08:40:46.531523+00:00 [running]> on host abduls-macbook-pro.local
[2024-12-02T13:40:51.292+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdul_Hanan_Nawaz' AIRFLOW_CTX_DAG_ID='etl_open_weather' AIRFLOW_CTX_TASK_ID='extract_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T08:40:46.531523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T08:40:46.531523+00:00'
[2024-12-02T13:40:51.294+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T13:40:51.314+0500] {logging_mixin.py:190} INFO - http://api.openweathermap.org/data/2.5/air_pollution/history?
[2024-12-02T13:40:51.315+0500] {logging_mixin.py:190} INFO - --Loading--Lahore_Data
[2024-12-02T13:41:56.631+0500] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-02T13:41:56.633+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T13:41:56.647+0500] {process_utils.py:132} INFO - Sending 15 to group 49559. PIDs of all processes in the group: [49559]
[2024-12-02T13:41:56.647+0500] {process_utils.py:87} INFO - Sending the signal 15 to group 49559
[2024-12-02T13:42:56.692+0500] {process_utils.py:150} WARNING - process psutil.Process(pid=49559, name='python3.12', status='running', started='13:40:51') did not respond to SIGTERM. Trying SIGKILL
[2024-12-02T13:42:56.695+0500] {process_utils.py:87} INFO - Sending the signal 9 to group 49559
[2024-12-02T13:42:56.711+0500] {process_utils.py:80} INFO - Process psutil.Process(pid=49559, name='python3.12', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:40:51') (49559) terminated with exit code -9
[2024-12-02T13:42:56.712+0500] {standard_task_runner.py:190} ERROR - ('Job 14 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
